"""Feature documentation and build summaries."""

from __future__ import annotations

from datetime import datetime, timezone

import pandas as pd

from src.features.feature_config import (
    FEATURE_GROUPS,
    FEATURE_REPORT_DIR,
    FIXTURE_FEATURES_PATH,
    MODEL_FEATURE_COLUMNS,
    TRAINING_DATASET_PATH,
    ensure_feature_directories,
)


def generate_feature_dictionary() -> str:
    ensure_feature_directories()
    lines = [
        "# Feature Dictionary",
        "",
        "| Feature | Group | Definition | Source columns | Historical | Fixtures | Leakage risk | Notes |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for feature in MODEL_FEATURE_COLUMNS:
        group = next((name for name in FEATURE_GROUPS if name in feature), "derived")
        lines.append(
            f"| `{feature}` | {group} | Engineered pre-match signal. | processed/intermediate data | yes | yes where available | low if built chronologically | Generated by Phase 3 feature pipeline. |"
        )
    path = FEATURE_REPORT_DIR / "feature_dictionary.md"
    path.write_text("\n".join(lines), encoding="utf-8")
    return str(path)


def generate_feature_build_summary(validation_status: str = "unknown", leakage_status: str = "unknown") -> str:
    ensure_feature_directories()
    training = pd.read_csv(TRAINING_DATASET_PATH) if TRAINING_DATASET_PATH.exists() else pd.DataFrame()
    fixtures = pd.read_csv(FIXTURE_FEATURES_PATH) if FIXTURE_FEATURES_PATH.exists() else pd.DataFrame()
    predictable = int(fixtures.get("is_predictable_now", pd.Series(dtype=bool)).fillna(False).sum()) if not fixtures.empty and "is_predictable_now" in fixtures else 0
    tbd = int(fixtures.get("fixture_has_tbd_team", pd.Series(dtype=bool)).fillna(False).sum()) if not fixtures.empty and "fixture_has_tbd_team" in fixtures else 0
    feature_count = len([c for c in training.columns if c in MODEL_FEATURE_COLUMNS]) if not training.empty else 0
    lines = [
        "# Feature Build Summary",
        "",
        f"- Build timestamp: {datetime.now(timezone.utc).replace(microsecond=0).isoformat()}",
        f"- Training dataset rows: {len(training)}",
        f"- Fixture dataset rows: {len(fixtures)}",
        f"- Configured model features present: {feature_count}",
        f"- Predictable 2026 fixtures now: {predictable}",
        f"- TBD fixture rows: {tbd}",
        f"- Validation status: {validation_status}",
        f"- Leakage check status: {leakage_status}",
        "",
        "## Outputs",
        "",
        f"- `{TRAINING_DATASET_PATH}`",
        f"- `{FIXTURE_FEATURES_PATH}`",
        "",
        "## Next Recommended Action",
        "",
        "Review validation/leakage reports before starting model training.",
    ]
    path = FEATURE_REPORT_DIR / "feature_build_summary.md"
    path.write_text("\n".join(lines), encoding="utf-8")
    return str(path)


def write_feature_summary() -> str:
    training = pd.read_csv(TRAINING_DATASET_PATH) if TRAINING_DATASET_PATH.exists() else pd.DataFrame()
    fixtures = pd.read_csv(FIXTURE_FEATURES_PATH) if FIXTURE_FEATURES_PATH.exists() else pd.DataFrame()
    predictable = int(fixtures.get("is_predictable_now", pd.Series(dtype=bool)).fillna(False).sum()) if not fixtures.empty and "is_predictable_now" in fixtures else 0
    tbd = int(fixtures.get("fixture_has_tbd_team", pd.Series(dtype=bool)).fillna(False).sum()) if not fixtures.empty and "fixture_has_tbd_team" in fixtures else 0
    feature_cols = [c for c in training.columns if c in MODEL_FEATURE_COLUMNS] if not training.empty else []
    lines = [
        "# Feature Summary",
        "",
        f"- Training dataset rows: {len(training)}",
        f"- Fixture dataset rows: {len(fixtures)}",
        f"- Number of configured features present: {len(feature_cols)}",
        f"- Predictable 2026 fixtures: {predictable}",
        f"- TBD fixtures: {tbd}",
        f"- Validation report: `outputs/reports/features/feature_validation_report.md`",
        f"- Leakage report: `outputs/reports/features/leakage_check_report.md`",
    ]
    path = FEATURE_REPORT_DIR / "feature_summary.md"
    path.write_text("\n".join(lines), encoding="utf-8")
    print("\n".join(lines[2:]))
    return str(path)
